"""
Reads 2D data (image generated by DM) and
converts it to 1D data
"""
import json
import os
import imageio
import numpy as np
import tqdm
from matplotlib import pyplot as plt

key_case = "wgan"
drive = "F:\\"
myPath_base = "UTSA\\paper3_DM"
temp = "paper3_data\case_{}_samples_2D".format(key_case)
myPath_save = os.path.join(drive, myPath_base, temp)
myPath_read = os.path.join(myPath_save, "case_{}_images_2D".format(key_case))
files = os.listdir(myPath_read)

temp_tot = []
for file in tqdm.tqdm(files):
    temp_path = os.path.join(myPath_read, file)
    with open(temp_path, 'r') as f:
        image_2d = imageio.imread(temp_path)
        image_2d_ch0 = image_2d[:, :, 0]
        temp = list(np.diagonal(image_2d_ch0)/255)
        temp_tot.append(temp)
        a = 0
exec('gb_dm_{} = temp_tot'.format(key_case))

dir_name = 'gb_dm_case_{}'.format(key_case)
file_name = 'gb_dm_1d_case_{}.json'.format(key_case)
temp_dir = os.path.join(myPath_save, dir_name)
os.makedirs(temp_dir, exist_ok=True)

temp = os.path.join(temp_dir, file_name)
with open(temp, 'w') as f:
    exec('json.dump(gb_dm_{}, f)'.format(key_case))
a = 0
